### ISSUE TITLE
Using different type of Data, needing different type of Transformers and Saving those difference

### ISSUE THREAD

**Issue by c-louis** [RubixML/ML#131]
Hi,

This issue name is certainly not perfect but I can't find a short name for my issue.

Here is my issue:

I have this kind of data :

`[string, string, float, LABEL]`

I want to use those transformers : 

`Rubix\ML\Transformers\TextNormalizer;`
`Rubix\ML\Transformers\WhitespaceTrimmer;`
`Rubix\ML\Transformers\WordCountVectorizer;`

For the two first strings.

After reading the doc a lot, I found something like that (Advanced Preprocessing) : 

Make a first labeled dataset with the two strings and the label.
Apply all the Transformers
Make a second Unlabeled dataset for the float
Join the second dataset to the first one. 

Then I create my estimators with 

`Rubix\ML\PersistentModel;`

But since my dataset is already "ready", I don't put anything in the pipeline transformers part.
Then I train my estimator and save it.

In another script I need to use the estimator. And here is where I'm lost, how can I prepare my sample(s) ?

I used to put all the transformers in the pipeline and it worked but can't use a float + 2 strings, so how can I use 2 strings and 1 float and still being able to predict things ?

Thanks for your time.
Louis

Edit:
My question is how can I use : 

> Advanced Preprocessing
> In some cases, certain features of a dataset may require a different set of preprocessing steps than the others. In such a case, we are able to extract only certain features, preprocess them, and then join them to another set of features. In the example below, we'll extract just the text reviews and their sentiment labels into a dataset object and put the sample's category, number of clicks, and ratings into a another using two Column Pickers. Then, we can apply a separate set of transformations to each set of features and use the join() method after to combine them into one dataset. We can even apply another set of transformation to the dataset after that.

And saving all those preprocessing things.

**Comment by c-louis** [comment]
And I just read the issue just under mine : 

https://github.com/RubixML/RubixML/issues/130#issue-724236347

And so I think maybe you can close my question is there is no way to do this for the moment and if there is a way, just tell me.

Thanks for your time again.
Louis

**Comment by andrewdalpino** [comment]
Hey @c-louis I believe your issue is solved in the issue you mentioned - here is the commit https://github.com/RubixML/RubixML/commit/32e8e857b9cfdd0cc0d1bf6740738a0167029814

Since this feature is only a day old (hasn't been released yet) you can install the *0.3.0.x-dev* branch and use the example found in the the issue https://github.com/RubixML/RubixML/issues/130#issue-724236347 as your guide. You can also browse the 0.3.0 docs (not released yet) in the link below.

https://docs.rubixml.com/en/0.3.0/preprocessing.html#persisting-fitted-transformers

Also feel free to join us in our Telegram channel if you'd like, we have a couple users with your similar scenario https://t.me/RubixML
