### ISSUE TITLE
Multilayer Perceptron is incompatible with categorical data types

### ISSUE THREAD

**Issue by P2T** [RubixML/ML#192]
Since v1.0, we cannot use Multilayer Perceptron estimator.

It throws an error : "incompatible with categorical data types".

Multilayer Perceptron is, in theory, a very good neural network for categorical data.

Why this change ?

**Comment by andrewdalpino** [comment]
Hey @P2T I'm not sure where you are getting your information from but MLPs do not support categorical features natively. Not now or in the past. Is it possible that you're mistaken?

**Comment by P2T** [comment]
Basically, in previous versions, OneHotEncoder was not necessary, that's my trouble.
Else, from Wikipedia : "MLPs are universal function approximators [...] when the response variable is categorical, MLPs make good classifier algorithms."

**Comment by andrewdalpino** [comment]
One Hot, or some other type of categorical feature encoding, would have been required in previous versions as well as MLPs do not support categorical features natively by design.

A simple but effective way to prove this is by the fact that matrix multiplication (or any linear algebraic operation for that matter) is not defined for categorical values.
