### ISSUE TITLE
Is it possible to save transformers?

### ISSUE THREAD

**Issue by drakon47** [RubixML/ML#53]
Greetings. I see is possible to save models trained for later use. Is there a way to save also trasnformers? For example, if I train a model using MaxAbsoluteScaler before, can I save the trasnformation so I can aply it to the predictions I would be performing on the already trained model? Thanks ahead for any help! Greetings. Martín.

**Comment by andrewdalpino** [comment]
Greetings @drakon47 and thank you for the question

Yes you can, but you'll need to wrap the transformations in a [Pipeline](https://docs.rubixml.com/en/latest/preprocessing.html#transformer-pipelines) and save the Pipeline in order to persist the transformer fittings for now

Having that said, the persistence subsystem has purposely been left pretty agnostic so that we can build it out once we better understand how Rubix engineers want to handle persistence

Since you were the first to bring the topic up, I'd love to get some feedback from you and the community ...

Should we allow individual transformers to be persisted in the same way a Learner would be?

Should we keep it the way it is? Only persist 'models?'

Should we do away with persistence and let the developer implement their own persistence?

Any other thoughts or comments would be helpful as well

Thanks again for the question

**Comment by drakon47** [comment]
Thank you Andrew for your answer. I checked the pipeline options but I think is not quite the answer. I think having persistent trasnformers can beq quite useful on porudctive enviroments. I´ll try to stage a situation:
Lets say I train a model that will be used later on a production enviroment for predictions purpouses. If I use an algorithm that needs the data to be trasnferomed before the training, for example values have to be normalized, I should be able to save the transformation information for later use because when I get new data for the prediction, that data should be normalized using the same parameters that were used on the training dataset.
It could be achieved outside the library, but I think that isn´t the idea. I hope Ive been clear and my comments help! Greetings.
Martin

**Comment by andrewdalpino** [comment]
Hi @drakon47 a [Pipeline](https://docs.rubixml.com/en/latest/pipeline.html) should handle the scenario you describe above just fine

Here's an example to further demonstrate ...

```php
use Rubix\ML\Pipeline;
use Rubix\ML\PersistentModel;
use Rubix\ML\Transformers\MaxAbsoluteScaler;
use Rubix\ML\Classifiers\GaussianNB;
use Rubix\ML\Persisters\Filesystem;

$estimator = new PersistentModel(
    new Pipeline([
        new MaxAbsoluteScaler(),
    ], new GaussianNB()),
    new Filesystem('example.model')
);

$estimator->train($dataset); // Transformers fitted automatically

$estimator->save(); // Pipeline including transformer fittings are persisted

...

$estimator = PersistentModel::load(new Filesystem('example.model')); // Pipeline with fittings loaded

$predictions = $estimator->predict($dataset); // Dataset transformed automatically
```

The [HAR](https://github.com/RubixML/HAR) example project demonstrates a persistable transformer pipeline as well

Also, see the section on [Model Persistence](https://docs.rubixml.com/en/latest/model-persistence.html)

**Comment by andrewdalpino** [comment]
Individual Stateful and Elastic Transformers are now Persistable as of 0.3.0 https://github.com/RubixML/RubixML/releases/tag/0.3.0
