### ISSUE TITLE
Not able to train GridSearch with KDNeighbors as base

### ISSUE THREAD

**Issue by AlmightyPeanut** [RubixML/ML#57]
Fatal error: Uncaught Error: Call to a member function bare() on null in [..]/composer/vendor/rubix/ml/src/Classifiers/KDNeighbors.php on line 116 Error

Here it should return "!$this->tree->bare()", but the tree of KDNeighbors is not set by the GridSearch so the tree is still null.

Trace:
17. Rubix\ML\GridSearch->train() MLModelManagementClass.inc:309
18. Rubix\ML\Other\Specifications\SamplesAreCompatibleWithEstimator::check() /composer/vendor/rubix/ml/src/GridSearch.php:251
19. Rubix\ML\GridSearch->compatibility() /composer/vendor/rubix/ml/src/Other/Specifications/SamplesAreCompatibleWithEstimator.php:23
20. Rubix\ML\GridSearch->trained() /composer/vendor/rubix/ml/src/GridSearch.php:200
21. Rubix\ML\Classifiers\KDNeighbors->trained() /composer/vendor/rubix/ml/src/GridSearch.php:214

Code:
`$grid = array(
	[5,6,7],
	[true],
	[new KDTree()]
);
$oModel = new GridSearch( KDNeighbors::class, $grid);
$oModel->train($oDataset);`

**Comment by andrewdalpino** [comment]
Thank you for the bug report @AllmightyPeanut 

There is a period of time between instantiation of Grid Search and when `train()` is called where Grid Search uses a proxy base estimator (instantiated without a constructor using reflection) to infer things like data type compatibility. Unfortunately, this is causing this exception because the Spatial tree object is not injected as a dependency when we use reflection in this way.

Thanks again for the great bug report, I should have a fix shortly

**Comment by AlmightyPeanut** [comment]
Thanks @andrewdalpino

**Comment by andrewdalpino** [comment]
This issue has been fixed with commit https://github.com/RubixML/RubixML/commit/c7cb857ea7ca9c8303471dd45f7539fc383428fa

@AllmightyPeanut you can install the latest dev-master to use this fix until we release 0.0.20. Let me know if there are any issues, but tested well on my end

Thanks again for the great bug report

**Comment by AlmightyPeanut** [comment]
It's working for me, thanks @andrewdalpino
