### ISSUE TITLE
something is not working as it should

### ISSUE THREAD

**Issue by GlauberF** [RubixML/ML#62]
the online demo on the site is not working, however the phrase and objective

![Captura de Tela_selecionar área_20200325160920](https://user-images.githubusercontent.com/11314585/77575736-bf3e8100-6eb2-11ea-808e-510d1c455c2d.png)

![Captura de Tela_selecionar área_20200325160931](https://user-images.githubusercontent.com/11314585/77575749-c36a9e80-6eb2-11ea-9e07-b8ccb3be147d.png)

**Comment by andrewdalpino** [comment]
@GlauberF 

More details would be helpful ... what is the behavior that you are expecting?

<img width="895" alt="Annotation 2020-03-25 175646" src="https://user-images.githubusercontent.com/18690561/77593348-10a23c80-6ec2-11ea-86e6-008ffe7ac0ab.png">
<img width="742" alt="Annotation 2020-03-25 175700" src="https://user-images.githubusercontent.com/18690561/77593352-11d36980-6ec2-11ea-8d70-2a57aab70f81.png">

**Comment by GlauberF** [comment]
was hoping it will return positive.

**Comment by andrewdalpino** [comment]
@GlauberF gotcha

I tried your exact phrase and the model returned positive

Given that the model is deterministic after training (and I have not updated the model since) it leads me to believe that the negative prediction is indeed for a different phrase than the one you screen captured

Having that said, it's reasonable to believe that any model will have some degree of error

Closing, since this doesn't appear to be an issue
