### ISSUE TITLE
Contacting the developer

### ISSUE THREAD

**Issue by SerafimArts** [RubixML/ML#73]
Because of your extreme arrogance, the excellent repository with the php-ml project has been deleted.

On this issue, I ask you to think about your behavior. And it’s extremely unpleasant that you behave like an offended child, although you yourself copied some code from php-ml without copyrights.

Personally, I am glad that I am inspiring someone with my code to develop something new. And it is extremely unpleasant that in the world of open source and the community of PHP such disputes arise.

I hope that those who see this text will think about how to act together in such situations in the future.

--- 

I am quite quick-tempered by nature, but tried to be more restrained in this post. In any case, you should know that I condemn your behavior.

**Comment by andrewdalpino** [comment]
Thanks for the feedback @SerafimArts I understand that it's a frustrating situation

We too were sad to see that the maintainer of PHP-ML chose to delete their repository rather than to make the changes that were requested.

I also understand that the author of PHP-ML has publicly made vague copyright claims but we have not received any notice. If the author wishes to claim copyright of any of our code, that is not trivial or fair use, he should contact me so we can sort it out.

Let me know if there's anything else I can help with
