### ISSUE TITLE
PHP Warning:  Division by zero in MulticlassBreakdown class. This warning eventually ends up breaking report generation

### ISSUE THREAD

**Issue by samuraya** [RubixML/ML#86]
Hi Andrew! I am aware that you updated the MulticlassBreakdown class with comments mentioning removal of division by zero checks. Curios to know if you caught any warnings or errors up until now after your recent update.
This ends up giving a warning and empty json report when calling $report->generate($predictions, $testing->labels()).

Thanks for the cool library by the way! I am using this for my research project

**Comment by andrewdalpino** [comment]
Hey @samuraya that's awesome what is your research project about?

Can you please post your code? Can you also post the full exception including line numbers? Can you also do a `count()` or `empty()` on the predictions and/or labels array to make sure it's not empty?

Once we get these key details I can start troubleshooting the issue you encountered.

**Comment by samuraya** [comment]
@andrewdalpino, here you go. FYI, I have tried data pre-processing with $data->apply method too, instead of doing it through Pipeline. Same outcome. Attached is the screenshot of the error

![Screenshot at 2020-07-16 22-24-03](https://user-images.githubusercontent.com/61466437/87690121-3cb83500-c7b3-11ea-99dd-e8976bf103ee.png)


Here is the code:

`<?php
include __DIR__ . '/../vendor/autoload.php';

use Rubix\ML\Datasets\Labeled;
use Rubix\ML\Extractors\CSV;
use Rubix\ML\Classifiers\KNearestNeighbors;
use Rubix\ML\Transformers\NumericStringConverter;
use Rubix\ML\Transformers\RobustStandardizer;
use Rubix\ML\Pipeline;

use Rubix\ML\CrossValidation\Reports\AggregateReport;
use Rubix\ML\CrossValidation\Reports\ConfusionMatrix;
use Rubix\ML\CrossValidation\Reports\MulticlassBreakdown;



$dataset = Labeled::fromIterator(new CSV('dataset.csv', true,';'));

[$training, $testing] = $dataset->stratifiedSplit(0.80);

$estimator = new Pipeline(
	[new NumericStringConverter(),new RobustStandardizer()], 
	new KNearestNeighbors(19)
);

$estimator->train($training);

$predictions = $estimator->predict($testing);

$report = new AggregateReport([
    new MulticlassBreakdown(),
    new ConfusionMatrix(),
]);

echo "number of items in predictions = ".count($predictions);
echo "<p>number of items in test labels = ".count($testing->labels());

$results = $report->generate($predictions, $testing->labels());
?>
`

in regard to my research, I am integrating machine learning services into existing opensource ERP systems. Maybe it will help small and medium sized businesses to realize some savings during current economic gloom

**Comment by andrewdalpino** [comment]
Thanks @samuraya sounds like you have a great project on your hands, keep it up!

So here is the failing code - for it to divide by zero both true positives and false positives have to be 0. It's a valid condition so I think I'll go ahead and put those checks back in.

![Annotation 2020-07-16 213631](https://user-images.githubusercontent.com/18690561/87742483-75084500-c7ac-11ea-8924-15773496f8d7.png)

As a side note, in order to obtain 0 true and false positives for a class that would mean the estimator never predicted that class yet there were at least 1 samples from the testing set that was labeled that class. How does your model perform on other classes or have you not gotten to that point yet?

**Comment by andrewdalpino** [comment]
Ok I reverted to the old method of substituting EPSILON for 0 to avoid the division by 0. Should be fixed in https://github.com/RubixML/RubixML/commit/ed6e7cf1959febb348629bc9895336f32fb5bdb5. You can download the latest dev-master from composer to try it out.

While I was working on this, I took a look at Scikit Learn to see how they handled this situation. It looks like they set the metric to 0 by default. 

![Annotation 2020-07-17 000244](https://user-images.githubusercontent.com/18690561/87750364-ddf9b800-c7c0-11ea-8d66-6b766228a510.png)

This is roughly equivalent to what we're doing with EPSILON substitution as 0 / EPSILON is still 0. This would not be true, however, if true positives didn't appear in both the numerator and denominator. Just making a note of that here for future reference.

Let me know if that solved the problem and thank you for the great bug report! Feel free to join our channel on Telegram https://t.me/RubixML :)

P.S. Have you tried [KD Neighbors](https://docs.rubixml.com/en/latest/classifiers/kd-neighbors.html) yet? It's a binary spatial tree-accelerated version of K Nearest Neighbors and it's way faster than brute-force KNN.

**Comment by samuraya** [comment]
glad to be of help. I will try the new version out.
I am using KNN for a demo example as it is easier to understand intuitively for readers. Otherwise, what you are saying completely makes sense.

**Comment by samuraya** [comment]
Ok, issue fixed!
