### ISSUE TITLE
Why `OneHotEncoder` creates 2 columns for binary data?

### ISSUE THREAD

**Issue by batata004** [RubixML/ML#97]
Hi,

I have a dataset with 1 column and that column is a binary with values "S" or "N". Why, when I use `OneHotEncoder` on that column, it created another column? I know the reason, but isnt that wrong? I mean, if a column has a binary data, using `OneHotEncoder` should only replace anything inside that column with "0" or "1" instead of creating another column.

For example, the first block of code below, results in a sample with 2 columns. If you replace that dataset with the dataset further down, it will not create a new column. At my understanding, these 2 datasets below are similar. So why one results in unnecessary column and the other does not?

```
$dataset_temp93 = new Labeled(

    [["S"],["S"],["N"],["S"],["N"]],
    ["sim","nao","nao","nao","sim"]
	
);

$transformer = new OneHotEncoder();
$dataset_temp93->apply($transformer);

var_dump($dataset_temp93);
```

```
$dataset_temp93 = new Labeled(

    [[0],[1],[0],[1],[1]],
    ["sim","nao","nao","nao","sim"]
	
);
```

**Comment by henrique-borba** [comment]
Hi @batata004,

@andrewdalpino can correct me but this happens because some operations (arithmetics, linear algebra...) requires aligned dimensions between the operands.

In some python libraries you would expect an vector, but internally during calculations this vector is *promoted* to a matrice (using atleast_2d method for example)

**Comment by andrewdalpino** [comment]
Each column created by [One Hot Encoder](https://docs.rubixml.com/en/latest/transformers/one-hot-encoder.html) represents the presence or non-presence of a category in a sample. Since a binary variable is just the special case of a categorical variable with strictly two choices, One Hot Encoder will encode this as two continuous columns. The value 0 representing the absence of the category represented by that column and a 1 representing the presence of the category represented at that column.

In the second example, you probably wouldn't want to one-hot encode it as it's already in continuous/numerical form. If you wanted to produce a binary representation of the categorical features in the first example, I'd use a binary encoding rather than a one-hot encoding such as `'1'` and `'0'` or `yes` and `no` for example.

We go over binary data as well as all the other data types in the docs in the section [Representing Your Data](https://docs.rubixml.com/en/latest/representing-your-data.html).

**Comment by batata004** [comment]
Great! Thank you!
